name: Run Tests with mamba

on:
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true  # Use mamba for faster dependency resolution
          # environment-file: environment.yml  # Replace with your environment file
          # activate-environment: myenv  # Replace 'myenv' with your Conda environment name

      # Step 3: Install additional dependencies (if required)
      - name: Install additional dependencies
        run: |
          mamba install pytest  # Ensure pytest is installed if not in environment.yml

      # Step 4: Run pytest
      - name: Run pytest
        run: |
          pytest
