name: Run Tests

on:
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  tests:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: condaenv
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      # - name: Create conda environment
      #   run: conda env create --name condaenv
      # - name: Activate conda environment
      #   run: conda activate condaenv
      - name: Install cadquery
        run: conda install -c conda-forge cadquery
      - name: Install pip dependencies
        run: pip install cqkit pytest
      - name: Install package
        run: pip install .
      - name: Run tests
        run: pytest tests
