name: Run Tests

on:
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  tests:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install cadquery
        run: conda install -c conda-forge cadquery
      - name: Install pip dependencies
        run: pip install cqkit pytest
      - name: List files
        run: ls -alh
      - name: Run tests
        run: pytest ../tests
